<!-- 
font-family: 'Quicksand', sans-serif;
font-family: 'Maitree', serif;
font-family: 'Muli', sans-serif;
-->

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Maitree|Muli|Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script>AOS.init();</script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <script
    src="http://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script src="js/addComment.js"></script>

    
    <link rel="stylesheet" href="css/auto-class.css">
    <link rel="stylesheet" href="css/layout.css">

   <title>Document</title>
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header_bloc">
                <div class="header_bloc_top">
                    <h1 class="t-a-center ud-p-50 c-black">LeBlog.<span>com</span></h1>
                </div>

                <nav class="header_bloc_nav ">                            
                    <ul class="fl-jc-b ud-p-20 normal-list">                        
                        <li><a class="normal-link c-black" href="index.php#about">A propos</a></li>
                        <li><a class="normal-link c-black" href="index.php">Accueil</a></li>
                        <li><a class="normal-link c-black" href="blog.php">Blog</a></li>
                        <li><a class="normal-link c-black" href="galery.php">Galerie photo</a></li>  
                        <li><a class="normal-link c-black" href="contact.php">Contact</a></li>
                        <?php if($_SESSION == true ): ?>


                            <?php if($_SESSION['role'] == 'admin' || $_SESSION['role'] == 'moderateur' || $_SESSION['role'] == 'writer'): ?>
                            <li><a class="normal-link c-black" href="profil.php"><?= $_SESSION['firstName'] ?>
                        
                                <?php if($_SESSION['role'] == 'admin'): ?>
                                    / admin
                                <?php endif ?>
                            <?php endif ?>
                            </a></li>
                            <li><a class="normal-link c-black" href="destroy.php">Deconnexion</a></li>
                        <?php elseif($_SESSION == false): ?>
                            <li><a class="normal-link c-black" href="user.php">Inscription / Connexion</a></li>
                        <?php endif ?>
                    </ul>
                </nav>
            </div>
        </div>
    </header>

    <main class="main">
        <?php include $template.".phtml" ?>
    </main>

    <footer>
        <div class="container">
            <p class="t-a-center ud-p-50">Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quos corrupti deleniti animi ratione maxime laborum, rem distinctio odit aut repellat suscipit, tempore ea voluptates ipsam placeat voluptatibus? Placeat quasi voluptate accusantium non, expedita alias ducimus delectus. Debitis, maxime quisquam.</p>
        </div>
    </footer>
    

    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</html>