<div class="container">
    <section class="modify_comment">
        
        <?php foreach($allPost as $allPosts): ?>
            <h3><?= $allPosts['title'] ?> // id : <?= $allPosts['id'] ?></h3>
            <p><?= $allPosts['author'] ?></p>
            <p><?= $allPosts['content'] ?></p>
            <p><?= $allPosts['publish_date'] ?></p>
            <p></p>

            <?php foreach()
        <?php endforeach ?>

        
    </section>
</div>  