
<div class="container">
    <section class="section_contact">
        <form class="section_contact_form w-50 m-auto" action="send_message.php" method="POST"> 
            <fieldset class="p-20 ud-m-50">
                <legend class="uppercase">Contact</legend>
                <div class="input_group m-auto fl-jc-b">
                    <input class="w-50 ud-m-10 p-10" type="text" name="firstName" placeholder="Votre prénom">
                    <input class="w-50 ud-m-10 p-10" type="text" name="lastName" placeholder="Votre nom">                    
                </div>

                <input class="w-100 ud-m-10 p-10" type="email" name="mail" placeholder="Votre mail">
                <input class="w-100 ud-m-10 p-10" type="text" name="subject" placeholder="Sujet du message">
                <textarea name="content" class="w-100 ud-m-10 p-10" rows="10" placeholder="Votre message"></textarea>

                <button class="p-10 ud-m-10 bg-c-black c-white" type="submit">Envoyer</button>
            </fieldset>
        </form>

        </form>
    </section>
</div>