<link rel="stylesheet" href="css/galery.css">

<div class="container">
    <section class="section_galery">
        <h1>Galerie photo</h1>
        <div class="section_galery_photo">
            <ul class="galery_photos normal-list fl-jc-b">
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="500" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="700" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
                <li data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200" class="w-30 ud-p-20"><img class="w-100" src="https://dummyimage.com/600x400/000/fff" alt=""></li>
            </ul>
        </div>
    </section>
</div>
