<link rel="stylesheet" href="css/index.css">
<div class="bloc_index ud-p-50 ">
    <div class="container">
        <section class="index_section bg-c-white c-black p-20  ud-m-50">
            <h1 class="ud-p-20 uppercase">Bievnenue sur mon blog fictif</h1>
            <p class="ud-p-50">Pour faciliter votre experience utilisateur sur ce site laissez vous guider et suivez les etapes.</p>
            <p>Pour une meilleur experience rendez vous sur la page d'<a href="user.php">inscription / connexion</a>.</p>
        </section>

        <section id="about" class="index_section_about">
            <div class="index_section_about_bloc fl-jc-b">
                <article class="index_section_about_bloc_article w-30 t-a-center">
                    <h3 class="ud-p-10">Lorem, ipsum dolor.</h3>
                    <img class="ud-p-10 w-100" src="https://dummyimage.com/600x400/000/fff" alt="">
                    <p class="ud-p-10">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt at possimus reiciendis iusto quod vel laboriosam autem ex ducimus nobis porro veritatis magnam est dolorum aspernatur eaque odio exercitationem laborum ut, excepturi neque voluptates itaque nihil. Inventore, sapiente commodi natus similique culpa minima accusantium odit. Earum aut dolore eum expedita.</p>
                </article>
                <article class="index_section_about_bloc_article w-30 t-a-center">
                    <h3 class="ud-p-10">Lorem, ipsum dolor.</h3>
                    <img class="ud-p-10 w-100" src="https://dummyimage.com/600x400/000/fff" alt="">
                    <p class="ud-p-10">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt at possimus reiciendis iusto quod vel laboriosam autem ex ducimus nobis porro veritatis magnam est dolorum aspernatur eaque odio exercitationem laborum ut, excepturi neque voluptates itaque nihil. Inventore, sapiente commodi natus similique culpa minima accusantium odit. Earum aut dolore eum expedita.</p>
                </article>
                <article class="index_section_about_bloc_article w-30 t-a-center">
                    <h3 class="ud-p-10">Lorem, ipsum dolor.</h3>
                    <img class="ud-p-10 w-100" src="https://dummyimage.com/600x400/000/fff" alt="">
                    <p class="ud-p-10">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt at possimus reiciendis iusto quod vel laboriosam autem ex ducimus nobis porro veritatis magnam est dolorum aspernatur eaque odio exercitationem laborum ut, excepturi neque voluptates itaque nihil. Inventore, sapiente commodi natus similique culpa minima accusantium odit. Earum aut dolore eum expedita.</p>
                </article>
            </div>
        </section>
    </div>
</div>